// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_YruM22cZWA6u0EkpcloaEvwE5em4BVo',
    appId: '1:1059952599628:android:1d5ddd0939425758f98ae9',
    messagingSenderId: '1059952599628',
    projectId: 'chating-app-b3e50',
    storageBucket: 'chating-app-b3e50.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbm9cQAKgDGKgk1G8jiVXp6xLy5RDPBIA',
    appId: '1:1059952599628:ios:4b2f7d0e2e42dbfbf98ae9',
    messagingSenderId: '1059952599628',
    projectId: 'chating-app-b3e50',
    storageBucket: 'chating-app-b3e50.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl3apL3SyjxyFBFVesqhylQonew0vBLqc',
    appId: '1:1059952599628:web:5093103320b20cf0f98ae9',
    messagingSenderId: '1059952599628',
    projectId: 'chating-app-b3e50',
    authDomain: 'chating-app-b3e50.firebaseapp.com',
    storageBucket: 'chating-app-b3e50.firebasestorage.app',
    measurementId: 'G-F7BNDNSME3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbm9cQAKgDGKgk1G8jiVXp6xLy5RDPBIA',
    appId: '1:1059952599628:ios:4b2f7d0e2e42dbfbf98ae9',
    messagingSenderId: '1059952599628',
    projectId: 'chating-app-b3e50',
    storageBucket: 'chating-app-b3e50.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl3apL3SyjxyFBFVesqhylQonew0vBLqc',
    appId: '1:1059952599628:web:ece738acec1dfcedf98ae9',
    messagingSenderId: '1059952599628',
    projectId: 'chating-app-b3e50',
    authDomain: 'chating-app-b3e50.firebaseapp.com',
    storageBucket: 'chating-app-b3e50.firebasestorage.app',
    measurementId: 'G-3MFWMHGKCF',
  );
}
